seed/Cargo.toml

Picks up latest fixes for disconnection.

seed: bump librad deps

---

Cargo.lock
seed/src/frontend.rs
seed/ui/src/Components/Peer.svelte

seed: Improvements

---

Cargo.lock
seed/Cargo.toml
seed/src/frontend.rs
seed/ui/src/Components/Avatar.svelte
seed/ui/src/Components/Peer.svelte
seed/ui/src/Components/Project.svelte
seed/ui/src/Components/User.svelte
seed/ui/src/Components/index.js
seed/ui/src/events.js

Avatars for peers and maintainers. Also refactored things a little bit to clean it up.

seed: Avatars!

---

seed/src/frontend.rs
seed/ui/package.json
seed/ui/src/App.svelte
seed/ui/src/Components/Peer.svelte
seed/ui/src/Components/PeerList.svelte
seed/ui/src/Components/User.svelte
seed/ui/src/state.js

Splits the list of peers into an online (shown on top) and a recently
seen list. On peer connection state change the peer is moved from one
list to another.

seed: connection list

---

seed/ui/src/state.js

Always use online peers for calculation.

seed: fix connected peer count

---

Cargo.lock
seed/Cargo.toml
seed/src/frontend.rs
seed/src/main.rs
seed/ui/src/Components/Header.svelte
seed/ui/src/state.js

See commits!
---
Depends on https://github.com/radicle-dev/radicle-link/pull/397

seed: Various fixes

---

seed/src/frontend.rs
seed/src/main.rs
seed/ui/src/Components/Header.svelte

The styling isn't ideal (the id is so long I had to shrink the font size a little), but we can solve that later.

seed: Format seed-id correctly and make copyable

---

.gitignore
seed/README.md

- keep the secret key in a dedicated place
- add extended usage docs

seed: Improve docs

---

.ci/clippy
.gitmodules
Cargo.lock
Cargo.toml
deny.toml
keyutil/Cargo.toml
seed/Cargo.toml

It turns out that we can avoid submodules, yielding a slightly nicer workflow.

Exploit cargo lock + patch instead of submodules for source dependencies

---

seed/ui/src/App.svelte
seed/ui/src/state.js

seed: avoid undefines when data not loaded

---

seed/ui/public/typography.css

Closes: https://github.com/radicle-dev/radicle-bins/issues/39.
| before | after |
|--------|------|
| <img width="1552" alt="Screenshot 2020-11-24 at 15 41 43" src="https://user-images.githubusercontent.com/158411/100109037-b9e36d00-2e6b-11eb-8006-e595d31cf7a6.png"> | <img width="1552" alt="Screenshot 2020-11-24 at 15 41 31" src="https://user-images.githubusercontent.com/158411/100109022-b51eb900-2e6b-11eb-8b27-1cbc56ace967.png"> |

seed: fix Firefox render bug

---

seed/ui/package.json
seed/ui/src/App.svelte
seed/ui/src/Components/Input.svelte
seed/ui/yarn.lock

Closes: #25.
Demo:
No projects at all:

seed: add filters

---

seed/ui/src/state.js

Prevents an exception which prevents the seed ui from loading.

seed: fix projects store default

---

seed/ui/src/App.svelte

| Before | After |
|-------|-------|
|<img width="1552" alt="Screenshot 2020-11-25 at 11 11 28" src="https://user-images.githubusercontent.com/158411/100213556-0cc23080-2f0f-11eb-89a1-576d77dd913c.png"> | <img width="1552" alt="Screenshot 2020-11-25 at 11 00 28" src="https://user-images.githubusercontent.com/158411/100213448-eac8ae00-2f0e-11eb-9e79-fce074c5d404.png"> |

seed: fix peer list header alignment

---

seed/ui/src/App.svelte

add banner to indicate replication issues

---

seed/src/frontend.rs

This is useful for pull-style monitoring. It's nicer to get the count of
peers and projects in a single request without having to parse the
specific json data.

Add an info endpoint for non-streaming stats

---

seed/src/main.rs

This allows passing a list of peers to the seed so you don't need to
wait for clients with hardcoded seed address to start gossiping.
This is step one towards implementing a periodic dump of known
connections to reload them after a seed node restart.
Relies on https://github.com/radicle-dev/radicle-link/pull/528

Expose the bootstrap list of peers as an argument

---

README.md
seed/ui/README.md

Add instructions for working on the UI to the main README

---

Cargo.lock

Pulls in critical network fixes for link.
Signed-off-by: Alexander Simmerl <a.simmerl@gmail.com>

Update deps including link

---

seed/src/frontend.rs

An error coming from the backend doesn't mean all hope is lost.
These are transient.

Don't panic!

---

seed/ui/src/App.svelte
seed/ui/src/Components/Copyable.svelte
seed/ui/src/Components/Header.svelte
seed/ui/src/Components/PeerList.svelte

It looks right on mobile (and all browser sizes) now. Would be cool if the seed address was truncated.
Closes #22

Mobile css

---

Cargo.lock
Cargo.toml
seed/Cargo.toml
seed/src/frontend.rs
seed/src/main.rs

Depends on radicle-dev/radicle-link#661

seed: improve resilience

---

seed/ui/src/App.svelte

closes #102 
Signed-off-by: Julien Donck <hello@juliendonck.com>

fix tabs-container max width

---

seed/src/frontend.rs

This makes the /projects/{urn} and /info paths available
for requesting from other websites, allowing for external UIs
to use seeds as data sources for project metadata as well as
querying the public state of a seed.
Note that these routes were already open/public, this simply
allows them to be queried from a browser as well.

[seed] Allow CORS requests for certain routes

---

Cargo.toml

Debugging symbols in release mode

---

Cargo.lock
Cargo.toml
deny.toml
rad/Cargo.toml
rad/src/main.rs

One ring to rule them all, one ring to bind them.
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>

rad: add rad binary
